name: Node.js CI/CD to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build (if TypeScript project)
    - name: Build TypeScript (optional)
      run: |
        if [ -f tsconfig.json ]; then
          npm run build
        else
          echo "No TypeScript project detected, skipping build"
        fi

    # Step 5: Verify secrets exist
    - name: Verify Azure secrets
      run: |
        if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ] || \
           [ -z "${{ secrets.AZURE_TENANT_ID }}" ] || \
           [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ] || \
           [ -z "${{ secrets.AZURE_CLIENT_SECRET }}" ]; then
          echo "One or more required Azure secrets are missing!"
          exit 1
        else
          echo "All required Azure secrets exist."
        fi

    # Step 6: Login to Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    # Step 7: Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: myapp-azure-nodejs        # Replace with your Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
